function saveVarsList = mkSaveVarsList

saveVarsList = {'bedRelDblFilteredTKETurb';...
    'bedRelDblFilteredTKEWave';
    'bedRelTKETurb';...
    'bedRelTKEWave';...
    'burstEndIndex';...
    'burstEnsembleNos'
    'burstMaxBins';...
    'burstMeanDepths';...
    'burstStartIndex';...
    'burstSurfBins';...
    'filterParameters';...
    'maxBinNo';...
    'maxNumBinsWithData';...
    'minNumBinsWithData';...
    'numEOFs';...
    'paramStruc';...
    'recordMeanDepth';...
    'sidelobeDepth';...
    'specFilterPassedTKE';...
    'specFilterStoppedTKE';...
    'surfRelFilterPassedTKE';...
    'surfRelFilterPassedTKETurb';...
    'surfRelFilterPassedTKEWave';...
    'surfRelTKETurb';...
    'surfRelTKEWave';...
    'surfRelADCPTKE';...
    'TKEEigenvals';...
    'TKEEigenvalsNormd';...
    'TKEEOFs';...
    'TKEExpanCoeffs';...
    'TKETruncnErr';...
    'wholeRecordADCPTKE';...
    'wholeRecordEnsNos';...
    'wholeRecordDatenums'};

end